var searchData=
[
  ['sarmfsw_20a_20href_20https_3a_20app_20travis_20ci_20com_20smfsw_20sarmfsw_20img_20src_20https_3a_20app_20travis_20ci_20com_20smfsw_20sarmfsw_20svg_20branch_20master_20alt_20build_20status_20a_0',['sarmfsw &lt;a href=&quot;https://app.travis-ci.com/SMFSW/sarmfsw&quot; &gt;&lt;img src=&quot;https://app.travis-ci.com/SMFSW/sarmfsw.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['sarmfsw_20img_20src_20https_3a_20app_20travis_20ci_20com_20smfsw_20sarmfsw_20svg_20branch_20master_20alt_20build_20status_20a_1',['sarmfsw &lt;a href=&quot;https://app.travis-ci.com/SMFSW/sarmfsw&quot; &gt;&lt;img src=&quot;https://app.travis-ci.com/SMFSW/sarmfsw.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['sarmfsw_20release_20notes_2',['sarmfsw (release notes)',['../md__release_notes.html',1,'']]],
  ['sarmfsw_20svg_20branch_20master_20alt_20build_20status_20a_3',['sarmfsw &lt;a href=&quot;https://app.travis-ci.com/SMFSW/sarmfsw&quot; &gt;&lt;img src=&quot;https://app.travis-ci.com/SMFSW/sarmfsw.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['smfsw_20sarmfsw_20img_20src_20https_3a_20app_20travis_20ci_20com_20smfsw_20sarmfsw_20svg_20branch_20master_20alt_20build_20status_20a_4',['sarmfsw &lt;a href=&quot;https://app.travis-ci.com/SMFSW/sarmfsw&quot; &gt;&lt;img src=&quot;https://app.travis-ci.com/SMFSW/sarmfsw.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['smfsw_20sarmfsw_20svg_20branch_20master_20alt_20build_20status_20a_5',['sarmfsw &lt;a href=&quot;https://app.travis-ci.com/SMFSW/sarmfsw&quot; &gt;&lt;img src=&quot;https://app.travis-ci.com/SMFSW/sarmfsw.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['src_20https_3a_20app_20travis_20ci_20com_20smfsw_20sarmfsw_20svg_20branch_20master_20alt_20build_20status_20a_6',['sarmfsw &lt;a href=&quot;https://app.travis-ci.com/SMFSW/sarmfsw&quot; &gt;&lt;img src=&quot;https://app.travis-ci.com/SMFSW/sarmfsw.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['status_20a_7',['sarmfsw &lt;a href=&quot;https://app.travis-ci.com/SMFSW/sarmfsw&quot; &gt;&lt;img src=&quot;https://app.travis-ci.com/SMFSW/sarmfsw.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]],
  ['svg_20branch_20master_20alt_20build_20status_20a_8',['sarmfsw &lt;a href=&quot;https://app.travis-ci.com/SMFSW/sarmfsw&quot; &gt;&lt;img src=&quot;https://app.travis-ci.com/SMFSW/sarmfsw.svg?branch=master&quot; alt=&quot;Build Status&quot;/&gt;&lt;/a&gt;',['../index.html',1,'']]]
];
